const data = [
  {
    name: "John",
    surname: "test",
    email: "john@example.com",
    password: "encrypted",
    phone: "01111111111",
    age: 18,
    country: "US",
    district: "New York",
    user_role: "ADMIN",
  },
  {
    name: "Jack",
    surname: "test2",
    email: "jack@example.com",
    password: "encrypted",
    phone: "01111111111",
    age: 28,
    country: "US",
    district: "Boston",
    user_role: "USER",
  },
  {
    name: "Michael",
    surname: "test3",
    email: "michael@example.com",
    password: "encrypted",
    phone: "01111111111",
    age: 23,
    country: "US",
    district: "Texas",
    user_role: "USER",
  },
  {
    name: "Sara",
    surname: "test4",
    email: "sara@example.com",
    password: "encrypted",
    phone: "01111111111",
    age: 18,
    country: "US",
    district: "New York",
    user_role: "ADMIN",
  },
  {
    name: "Peter",
    surname: "test5",
    email: "peter@example.com",
    password: "encrypted",
    phone: "01111111111",
    age: 42,
    country: "US",
    district: "New York",
    user_role: "USER",
  },
];

module.exports = data;
